#ifndef CMAKECONFIG_HPP
#define CMAKECONFIG_HPP

    #ifdef ROOT_PATH_CMAKE
    #define ROOT_PATH QT_STRINGIFY(ROOT_PATH_CMAKE)
    #else
    #define ROOT_PATH ""
    #endif

    #ifdef MAX_CREDENTIAL_LENGTH_CMAKE
    #define MAX_CREDENTIAL_LENGTH MAX_CREDENTIAL_LENGTH_CMAKE
    #else
    #define MAX_CREDENTIAL_LENGTH -1
    #endif

#endif // CMAKECONFIG_HPP
